global:
  scrape_interval:     15s # 默认抓取周期
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'node-exporter' #服务的名称
    scrape_interval: 5s
    metrics_path: /metrics  #获取指标的url
    static_configs:
      - targets: ['node-exporter:9100'] # 这个为监听指定服务服务的ip和port，需要修改为自己的ip，貌似云服务必须用公网ip

  - job_name: 'prometheus' #服务的名称
    scrape_interval: 5s
    metrics_path: /metrics  #获取指标的url
    static_configs:
      - targets: [ 'prometheus:9090' ] # 这个为监听指定服务服务的ip和port，需要修改为自己的ip，貌似云服务必须用公网ip


