CREATE TABLE `bill`
(
    `id`                         bigint(20)   NOT NULL COMMENT '主键',
    `code`                       varchar(255)             DEFAULT NULL COMMENT '工单编号：客户+日期+随机序列',
    `content`                    varchar(500)             DEFAULT NULL COMMENT '工单内容',
    `phone`                      varchar(255)             DEFAULT NULL COMMENT '联系电话',
    `source`                     varchar(255)             DEFAULT NULL COMMENT '单据来源',
    `informant_type`             varchar(255)             DEFAULT NULL COMMENT '报单人类型（员工，业主，租户、租户成员，业主成员、外部人员）',
    `informant_name`             varchar(255)             DEFAULT NULL COMMENT '报单人姓名',
    `informant_id`               bigint(20)               DEFAULT NULL COMMENT '报单人id',
    `org_name`                   varchar(255)             DEFAULT NULL COMMENT '组织名称',
    `informant_time`             datetime                 DEFAULT NULL COMMENT '报单时间',
    `prepared_id`                bigint(20)               DEFAULT NULL COMMENT '制单人id',
    `prepared_name`              varchar(255) NOT NULL COMMENT '制单人姓名',
    `prepared_time`              datetime                 DEFAULT NULL COMMENT '制单时间',
    `org_id`                     bigint(20)               DEFAULT NULL COMMENT '组织id',
    `project_id`                 bigint(20)               DEFAULT NULL COMMENT '项目id',
    `project_name`               varchar(255)             DEFAULT NULL COMMENT '项目名称',
    `house_id`                   bigint(20)               DEFAULT NULL COMMENT '房屋id',
    `house_name`                 varchar(255)             DEFAULT NULL COMMENT '房屋全称',
    `position_desc`              varchar(255)             DEFAULT NULL COMMENT '位置描述',
    `owner_id`                   bigint(20)               DEFAULT NULL COMMENT '业户id',
    `owner_name`                 varchar(255)             DEFAULT NULL COMMENT '业户姓名',
    `relation`                   varchar(255)             DEFAULT NULL COMMENT '业户关系',
    `work_type_parent_id`        bigint(20)               DEFAULT NULL COMMENT '一级类型id',
    `work_type_parent_name`      varchar(255)             DEFAULT NULL COMMENT '一级类型名称',
    `work_type_set_id`           bigint(20)               DEFAULT NULL COMMENT '项目一级类型id',
    `work_type_parent_alias`     varchar(255)             DEFAULT NULL COMMENT '一级类型别名',
    `work_type_second_id`        bigint(20)               DEFAULT NULL COMMENT '二级工单类型id',
    `work_type_second_name`      varchar(255)             DEFAULT NULL COMMENT '二级工单类型名称',
    `work_type_id`               bigint(20)               DEFAULT NULL COMMENT '单据类别',
    `work_type_name`             varchar(255)             DEFAULT NULL COMMENT '工单类型名称',
    `work_type_full_name`        varchar(255)             DEFAULT NULL COMMENT '工单类型全名',
    `appointment`                bit(1)                   DEFAULT NULL COMMENT '是否预约',
    `appointment_time`           datetime                 DEFAULT NULL COMMENT '预约时间',
    `paid`                       bit(1)                   DEFAULT NULL COMMENT '是否有偿',
    `urgent`                     bit(1)                   DEFAULT NULL COMMENT '是否紧急',
    `generate_fee`               bit(1)                   DEFAULT NULL COMMENT '是否生成财务应收',
    `charge_object`              varchar(255)             DEFAULT NULL COMMENT '收费对象',
    `total_cost`                 double(10, 2)            DEFAULT NULL COMMENT '费用总额',
    `labor_cost`                 double(10, 2)            DEFAULT NULL COMMENT '人工费',
    `material_cost`              double(10, 2)            DEFAULT NULL COMMENT '材料费',
    `other_cost`                 double(10, 2)            DEFAULT NULL COMMENT '其他费',
    `pay_status`                 varchar(255)             DEFAULT NULL COMMENT '支付状态',
    `pay_type`                   varchar(255)             DEFAULT NULL COMMENT '支付方式名称',
    `rework`                     bit(1)                   DEFAULT b'0' COMMENT '是否返工',
    `rework_times`               int(11)                  DEFAULT '0' COMMENT '返工次数',
    `status`                     varchar(255)             DEFAULT NULL COMMENT '当前状态',
    `print_times`                int(11)                  DEFAULT '0' COMMENT '打印次数',
    `locked`                     bit(1)                   DEFAULT NULL COMMENT '是否锁定',
    `lock_reason`                varchar(255)             DEFAULT NULL COMMENT '锁定原因',
    `suspend`                    bit(1)                   DEFAULT NULL COMMENT '是否挂起',
    `suspend_id`                 bigint(20)               DEFAULT NULL COMMENT '挂起人id',
    `in_pool`                    bit(1)                   DEFAULT b'1' COMMENT '是否进入工单池',
    `normal_hours`               double(255, 0)           DEFAULT NULL COMMENT '标准工时',
    `performance`                double(255, 0)           DEFAULT NULL COMMENT '绩效',
    `over_time1`                 datetime                 DEFAULT NULL COMMENT '当前状态一级超时时间',
    `over_time2`                 datetime                 DEFAULT NULL COMMENT '当前状态二级超时时间',
    `over_time3`                 datetime                 DEFAULT NULL COMMENT '当前状态三级超时时间',
    `over_time_level`            varchar(255)             DEFAULT NULL COMMENT '超时等级',
    `bill_detail_id`             bigint(20)               DEFAULT NULL COMMENT '最新的工单处理详情id',
    `allow_add_time`             bit(1)                   DEFAULT NULL COMMENT '是否允许追加工时',
    `add_flag`                   bit(1)                   DEFAULT NULL COMMENT '是否追加工时',
    `add_duration`               int(11)                  DEFAULT NULL COMMENT '追加工时分钟数',
    `add_status`                 varchar(255)             DEFAULT NULL COMMENT '追加工时审批状态',
    `add_reason`                 varchar(255)             DEFAULT NULL COMMENT '追加工时原因',
    `dispatcher_id`              bigint(20)               DEFAULT NULL COMMENT '派单人id',
    `dispatcher_name`            varchar(255)             DEFAULT NULL COMMENT '派单人姓名',
    `receiver_id`                bigint(20)               DEFAULT NULL COMMENT '指派给(接单人id)',
    `receiver_name`              varchar(255)             DEFAULT NULL COMMENT '指派给(接单人name)',
    `close_type_id`              bigint(20)               DEFAULT NULL COMMENT '闭单类型id',
    `close_type_name`            varchar(255)             DEFAULT NULL COMMENT '闭单类型名称',
    `close_reason`               varchar(1000)            DEFAULT NULL COMMENT '闭单原因',
    `close_doc_remark`           varchar(255)             DEFAULT NULL COMMENT '闭单文件说明',
    `abnormal_close`             bit(1)                   DEFAULT b'0' COMMENT '是否异常关闭',
    `tenant_id`                  bigint(20)   NOT NULL COMMENT '租户id',
    `begin_time`                 datetime                 DEFAULT NULL COMMENT '开始时间',
    `end_time`                   datetime                 DEFAULT NULL COMMENT '结束时间',
    `duration`                   double(20, 0)            DEFAULT NULL COMMENT '维修时长',
    `overtime`                   bit(1)                   DEFAULT NULL COMMENT '是否超时',
    `have_material`              bit(1)                   DEFAULT NULL COMMENT '是否有物料',
    `evaluate_result`            int(10)                  DEFAULT NULL COMMENT '评价结果评分',
    `auto_evaluate`              bit(1)                   DEFAULT NULL COMMENT '是否自动',
    `supervised`                 bit(1)                   DEFAULT NULL COMMENT '是否督办',
    `visit_satisfaction`         int(1) unsigned zerofill DEFAULT NULL COMMENT '回访满意度',
    `reinforced`                 bit(1)                   DEFAULT NULL COMMENT '是否已成功呼叫增援',
    `transfer_times`             int(6)                   DEFAULT NULL COMMENT '转单次数',
    `warn1`                      datetime                 DEFAULT NULL COMMENT '一级超时预警时间',
    `warn2`                      datetime                 DEFAULT NULL COMMENT '二级超时预警时间',
    `warn3`                      datetime                 DEFAULT NULL COMMENT '三级超时预警时间',
    `business_source`            varchar(255)             DEFAULT NULL COMMENT '业务来源',
    `business_source_id`         bigint(20)               DEFAULT NULL COMMENT '业务来源id',
    `equipment_id`               bigint(20)               DEFAULT NULL COMMENT '设备id',
    `equipment_name`             varchar(255)             DEFAULT NULL COMMENT '设备名称',
    `inspection_point_id`        bigint(20)               DEFAULT NULL COMMENT '巡检点id',
    `inspection_point_name`      varchar(255)             DEFAULT NULL COMMENT '巡检点名称',
    `other_bill_id`              bigint(20)               DEFAULT NULL COMMENT '业务单据id',
    `doc_name`                   varchar(255)             DEFAULT NULL COMMENT '文档名称',
    `doc_path`                   varchar(255)             DEFAULT NULL COMMENT '文档文件路径',
    `doc_html_path`              varchar(255)             DEFAULT NULL COMMENT '文档html路径',
    `doc_gen_time`               datetime                 DEFAULT NULL COMMENT '文档生成时间',
    `doc_id`                     bigint(20)               DEFAULT NULL COMMENT '文档id',
    `over_time_id`               char(50)                 DEFAULT NULL COMMENT '超时定时任务id',
    `over_warn_time_id`          char(50)                 DEFAULT NULL COMMENT '超时警告定时任务id',
    `confirm_id`                 bigint(20)               DEFAULT NULL COMMENT '确认人id',
    `confirm_result`             varchar(50)              DEFAULT NULL COMMENT '确认结果',
    `confirm_name`               varchar(255)             DEFAULT NULL COMMENT '确认人名称',
    `suspend_audit_id`           bigint(20)               DEFAULT NULL COMMENT '挂起审核单id',
    `close_audit_id`             bigint(20)               DEFAULT NULL COMMENT '关闭审核单id',
    `paid_to_unpaid_audit_id`    bigint(20)               DEFAULT NULL COMMENT '有偿转无偿审核单id',
    `add_time_audit_id`          bigint(20)               DEFAULT NULL COMMENT '加时审核单id',
    `delay_application_audit_id` bigint(20)               DEFAULT NULL COMMENT '延期申请审核单id',
    `create_time`                datetime                 DEFAULT NULL COMMENT '创建时间',
    `create_id`                  bigint(20)               DEFAULT NULL COMMENT '创建人id',
    `create_name`                varchar(255)             DEFAULT NULL COMMENT '创建人姓名',
    `modifier_time`              datetime                 DEFAULT NULL COMMENT '修改时间',
    `modifier_id`                bigint(20)               DEFAULT NULL COMMENT '修改人id',
    `modifier_name`              varchar(255)             DEFAULT NULL COMMENT '修改人姓名',
    `receive_over`               tinyint(1)               DEFAULT NULL COMMENT '接单是否超时',
    `complete_over`              tinyint(1)               DEFAULT NULL COMMENT '完成是否超时',
    `on_schedule_time`           datetime                 DEFAULT NULL COMMENT '到期应完成时间',
    `handle_hours`               double                   DEFAULT NULL COMMENT '处理时限',
    `build_id`                   bigint(20)               DEFAULT NULL COMMENT '楼栋id',
    `unit_id`                    bigint(20)               DEFAULT NULL COMMENT '单元id',
    `floor_id`                   bigint(20)               DEFAULT NULL COMMENT '楼层id',
    `recording_id`               varchar(255)             DEFAULT NULL COMMENT '关联录音的id',
    `recording_address`          varchar(255)             DEFAULT NULL COMMENT '录音链接',
    `ext_id`                     varchar(255)             DEFAULT NULL COMMENT '外部系统id',
    `extsource`                  varchar(255)             DEFAULT NULL COMMENT '外部来源',
    `ext_memo`                   varchar(255)             DEFAULT NULL COMMENT '外部描述',
    `longitude`                  varchar(20)              DEFAULT NULL COMMENT '经度',
    `latitude`                   varchar(20)              DEFAULT NULL COMMENT '维度',
    PRIMARY KEY (`id`) USING BTREE,
    KEY `project_id` (`project_id`) USING BTREE,
    KEY `tenant_id` (`tenant_id`) USING BTREE,
    KEY `bill_detail_id` (`bill_detail_id`) USING BTREE,
    KEY `bill_work_type_second_id_index` (`work_type_second_id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  ROW_FORMAT = DYNAMIC;